name: "CI"

on: [push, pull_request]

env:
  PROJECT_PATH: 'Hrimsoft.StringCases/Hrimsoft.StringCases.csproj'
  TESTS_PROJECT_PATH: 'Hrimsoft.StringCases.Tests/Hrimsoft.StringCases.Tests.csproj'
  
jobs:
  build:
    name: 'Build'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: 'Unit tests'
      run: dotnet test ${{ env.TESTS_PROJECT_PATH }}